#!/usr/bin/env ruby -s

# =====  Half-assed help screen  =====
instructions = <<INSTRUCTIONS
Example:
$ ./run -w=20 -h=30
INSTRUCTIONS

at_exit { puts instructions if $! && !$!.kind_of?(SystemExit) }

if $h == true
  puts instructions
  exit
end


require_relative 'maze'

# =====  pretty drawing  =====
clear       = "\e[H\e[2J"
hide_cursor = "\e[?25l"
show_cursor = "\e[?25h"
print hide_cursor, clear
at_exit { print show_cursor }

# =====  Record randomness  =====
seed = Random::DEFAULT.seed
Random.srand seed
# Random.srand 86057636662888991353196408997421009309 bfs with 40/40 is really nice with this srand
at_exit { puts "Seed to get this maze again: #{seed}" }

# ===== Main  =====
width  = ($w || 40).to_i
height = ($h || 40).to_i

maze, start, finish = build_maze width, height
*failed_paths, path = depth_first_search maze, start, finish


failed_paths.each do |failed_path|
  display maze, heading: {text: 'Path', colour: :blue},
                green:   [start, finish],
                red:     failed_path,
                blue:    path
  sleep 1
end
