#!/usr/bin/env ruby -s

default_width  = 40
default_height = 30

maze_width  = ($w || default_width).to_i
maze_height = ($h || default_height).to_i
random_seed = ($s || Random::DEFAULT.seed).to_i

# =====  Half-assed help screen  =====
instructions = <<INSTRUCTIONS
Example:
  # use defaults
  $ ./run

  # set all the things!
  $ ./run -w=20 -h=30 -s=

Options
  -w=123       # Set the maze width (defaults to #{default_width})
  -h=123       # Set the maze height (defaults to #{default_height})
  -s=123       # SEt the random seed (defaults to whatever Ruby initializes it with)
INSTRUCTIONS

# at_exit { puts instructions if $! && !$!.kind_of?(SystemExit) }

if $h == true
  puts instructions
  exit
end


require_relative 'maze'

# =====  pretty drawing  =====
clear       = "\e[H\e[2J"
hide_cursor = "\e[?25l"
show_cursor = "\e[?25h"
print hide_cursor, clear
at_exit { print show_cursor }

# =====  Record randomness  =====
Random.srand random_seed
at_exit { puts "call with -s=#{random_seed} to get this maze again" }

# ===== Main  =====
display = Display.new(enable: true, stream: $stdout)
maze    = GenerateMaze.call width: maze_width, height: maze_height, display: display

display.call maze: maze

maze.breadth_first_search(maze.start, maze.finish)
